import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  // CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    if (!GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY environment variable is missing.");
    }

    const { startDate, daysToGenerate, firstPairIds, availableConsultantsIds, excludedConsultantsIds = [] } = await req.json();

    if (!startDate || !daysToGenerate || !firstPairIds || !availableConsultantsIds) {
      throw new Error("Missing required parameters in request body.");
    }

    const modelName = "gemini-3-flash-preview";
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${GEMINI_API_KEY}`;

    const systemPrompt = `
You are an expert workforce scheduler. Generate a JSON array containing a 30-day work schedule.

RULES:
1. Work Days: Monday to Saturday.
2. Sundays are ALWAYS off (skip them entirely from the output array).
3. "Carga" shift requires EXACTLY 2 people.
4. "Carga" shift time is 08:30:00 to 17:30:00.
5. "Normal" shift time is 09:30:00 to 18:30:00.
6. NEW "Carga" assignments happen ONLY on Mondays, Wednesdays, and Fridays.
7. On Tuesdays, Thursdays, and Saturdays, the 2 people who did "Carga" on the PREVIOUS DAY must repeat the EXACT SAME 08:30:00 to 17:30:00 shift (this is the "Espelho" or mirror shift).
8. Use a round-robin rotation for the "Carga" shift among the available consultants.
9. Everyone else works the "Normal" shift (09:30:00 to 18:30:00).
10. If someone is in the 'excludedConsultantsIds' list, they must NOT appear in the schedule at all (they are on vacation/medical leave).

INPUTS:
- Start Date: ${startDate} (This is a Monday)
- Days to generate: ${daysToGenerate}
- The first 2 people for Carga on the Start Date are EXACTLY: ${JSON.stringify(firstPairIds)}
- List of all available consultants (UUIDs): ${JSON.stringify(availableConsultantsIds)}
- List of excluded consultants (UUIDs): ${JSON.stringify(excludedConsultantsIds)}

OUTPUT FORMAT:
Respond ONLY with a raw JSON array of objects. Do not use markdown blocks (\`\`\`json). Just the raw JSON.
Each object must have this EXACT structure:
{
  "date": "YYYY-MM-DD",
  "user_id": "uuid-of-consultant",
  "is_carga": true/false, // true if they work 08:30-17:30 (carga or mirror), false if 09:30-18:30
  "shift_start": "08:30:00" or "09:30:00",
  "shift_end": "17:30:00" or "18:30:00"
}
Every available consultant (not excluded) must have 1 object per working day in the array.
`;

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: "Please generate the schedule based on the system instructions." }]
          }
        ],
        systemInstruction: {
          parts: [{ text: systemPrompt }]
        },
        generationConfig: {
          temperature: 0.1, // Low temperature for deterministic output
          responseMimeType: "application/json",
        }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API Error:", errorText);
      throw new Error(`Google API returned ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error("No text generated by Gemini API");
    }

    let scheduleData;
    try {
      scheduleData = JSON.parse(generatedText);
    } catch (e) {
      console.error("Failed to parse Gemini output as JSON:", generatedText);
      throw new Error("AI returned invalid JSON format.");
    }

    return new Response(
      JSON.stringify({ schedule: scheduleData }),
      { 
        headers: { ...corsHeaders, "Content-Type": "application/json" }
      }
    );
  } catch (error: any) {
    console.error("Function error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { 
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" } 
      }
    );
  }
});
