const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");

if (!GEMINI_API_KEY) {
  console.error("GEMINI_API_KEY environment variable is missing.");
}

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface MessagePart {
  text?: string;
  inlineData?: {
    mimeType: string;
    data: string;
  };
}

interface ChatMessage {
  role: "user" | "model";
  parts: MessagePart[];
}

interface RequestBody {
  message: string;
  systemMessage: string;
  images?: string[]; // array of base64 strings
  history?: ChatMessage[];
}

Deno.serve(async (req) => {
  // CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const body = await req.json() as RequestBody;
    const message = body.message;
    const systemMessage = body.systemMessage;
    const images = body.images || [];
    const history = body.history || [];

    if (!message) {
      throw new Error("Message is required");
    }

    const modelName = "gemini-3-flash-preview";
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${GEMINI_API_KEY}`;

    // Format the current message
    const currentMessageParts: MessagePart[] = [{ text: message }];

    // Attach images if provided
    for (const img of images) {
      // Assuming format: "data:image/jpeg;base64,..."
      let mimeType = "image/jpeg";
      let base64Data = img;
      
      if (img.startsWith("data:")) {
        const parts = img.split(";base64,");
        if (parts.length === 2) {
          mimeType = parts[0].replace("data:", "");
          base64Data = parts[1];
        }
      }
      
      if (base64Data) {
        currentMessageParts.push({
          inlineData: {
            mimeType,
            data: base64Data
          }
        });
      }
    }

    const currentTurn: ChatMessage = {
      role: "user",
      parts: currentMessageParts,
    };

    const contents = [...history, currentTurn];

    console.log(`Calling Gemini API (${modelName}) with message length:`, message.length);

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        systemInstruction: {
          parts: [{ text: systemMessage }]
        },
        contents: contents,
        generationConfig: {
          temperature: 0.7,
        }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API Error:", errorText);
      throw new Error(`Google API returned ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error("No text generated by Gemini API");
    }

    return new Response(
      JSON.stringify({ text: generatedText }),
      { 
        headers: { ...corsHeaders, "Content-Type": "application/json" }
      }
    );
  } catch (error) {
    console.error("Function error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { 
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" } 
      }
    );
  }
});